### ISSUE TITLE
Server "name" isn't the registered server name

### ISSUE THREAD

**Issue by pljones** [softins/jamulus-php#2]
It appears that the server `name` in the response is the value in the request for individual servers.  Does the server response not include its name?  (I'm not that fussed -- for my own purposes, I can hard code the server name in my site display.)

https://explorer.jamulus.io/servers.php?server=jamulus.drealm.info:54850
```
[
  {
    "index": 0,
    "name": "jamulus.drealm.info",
    "numip": 1370397608,
    "ip": "81.174.155.168",
    "port": 54850,
    "ping": 9, "os": "Linux", "version": "3.6.1git", "versionsort": "003006001git", "nclients": 0
  }
]
```
https://explorer.jamulus.io/servers.php?server=81.174.155.168:54850
```
[
  {
    "index": 0,
    "name": "81.174.155.168",
    "numip": 1370397608,
    "ip": "81.174.155.168",
    "port": 54850,
    "ping": 8, "os": "Linux", "version": "3.6.1git", "versionsort": "003006001git", "nclients": 0
  }
]
```

**Comment by softins** [comment]
Only just noticed this issue. The server name configured in Jamulus with `--serverinfo` or `-o` is only ever sent to the Central Server, when registering. There is no message defined in the protocol for a client to request the server info directly from a server.

So for that reason, we can only return the configured server name when it is given by a Central Server. When querying an individual server, the hostname or IP is returned in the `name` field, in preference to not returning anything.

**Comment by softins** [comment]
I'll close this for now. It could be reopened if the Jamulus protocol is ever extended to provide a way to fetch server info directly from a server.
